### PR TITLE
feat. Update fuzzdb imports to use importlib/pathlib, add types

### PR DESCRIPTION
**Pull request by jscanlannyc**
This update changes this module to use importlib, pathlib, and context
managers for file reading from fuzzdb.

This also adds type annotations to all functions in this module.

This has passed tests for this module and has passed through `mypy` for
type validation and `black` for formatting.

### CODE REVIEW

**Comment by woodruffw** [comment]
Hmm. Looks like some of the APIs are Python 3.9 and newer?

```
======================================================================
ERROR: test_repeated_msg (test_protofuzz.TestProtofuzz)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/protofuzz/protofuzz/protofuzz/tests/test_protofuzz.py", line 172, in test_repeated_msg
    for msg in messages[name].linear(limit=10):
  File "/home/runner/work/protofuzz/protofuzz/protofuzz/protofuzz.py", line 186, in _iteration_helper
    generator = descriptor_to_generator(self._descriptor, iter_class)
  File "/home/runner/work/protofuzz/protofuzz/protofuzz/protofuzz.py", line 125, in descriptor_to_generator
    generator = _prototype_to_generator(descriptor, cls)
  File "/home/runner/work/protofuzz/protofuzz/protofuzz/protofuzz.py", line 113, in _prototype_to_generator
    generator = descriptor_to_generator(descriptor.message_type, cls)
  File "/home/runner/work/protofuzz/protofuzz/protofuzz/protofuzz.py", line 125, in descriptor_to_generator
    generator = _prototype_to_generator(descriptor, cls)
  File "/home/runner/work/protofuzz/protofuzz/protofuzz/protofuzz.py", line 99, in _prototype_to_generator
    generator = _int_generator(descriptor, bitwidth, unsigned)
  File "/home/runner/work/protofuzz/protofuzz/protofuzz/protofuzz.py", line 44, in _int_generator
    vals = list(values.get_integers(bitwidth, unsigned))
  File "/home/runner/work/protofuzz/protofuzz/protofuzz/values.py", line 136, in get_integers
    for num in _fuzzdb_integers(limit):
  File "/home/runner/work/protofuzz/protofuzz/protofuzz/values.py", line 81, in _fuzzdb_integers
    path = _get_fuzzdb_path() / Path("integer-overflow/integer-overflows.txt")
  File "/home/runner/work/protofuzz/protofuzz/protofuzz/values.py", line 54, in _get_fuzzdb_path
    str(importlib.resources.files(package_name).joinpath(module_name))
AttributeError: module 'importlib.resources' has no attribute 'files'
```

https://docs.python.org/3/library/importlib.html#importlib.resources.files

(This is not a big deal IMO. I'm perfectly happy making this project require 3.9 or newer; I'll tweak the CI now.)

**Comment by woodruffw** [comment]
If you rebase or merge, the CI should pass here. Otherwise LGTM!

**Comment by jscanlannyc** [comment]
Yes, unfortunately the API to access the package members directly was made available in 3.9 and I had coded my changes against it. 

I have rebased and updated my branch for your CI changes.

**Comment by jscanlannyc** [comment]
Would you also like me to update the README for the env instructions?

**Comment by woodruffw** [comment]
> Would you also like me to update the README for the env instructions?

Yep, that would be great.

**Review by woodruffw — APPROVED** [review]

**Comment by woodruffw** [comment]
Thanks for these changes! Let me know if a new release on PyPI would help with your use case.

**Pull request merged**
